#!/bin/bash

set -eu

_args=()

if [ -d policy ]; then
	policy_name=$(basename $(readlink -f policy))
	_args+=(--tag $policy_name)

	if [ -f "policy/clean_args" ]; then
		mapfile -t -O ${#_args[@]} _args < policy/clean_args
	fi
fi

if [ -f clean_args ]; then
	mapfile -t -O ${#_args[@]} _args < clean_args
fi

set -x
exec restic forget \
	${_args[*]} \
	"$@"
