#!/bin/bash

set -eu

declare -a _args

if [ -f exclude ]; then
	_args+=(--exclude-file exclude)
fi

if [ -d policy ]; then
	policy_name=$(basename $(readlink -f policy))
	_args+=(--tag $policy_name)

	if [ -f "policy/backup_args" ]; then
		mapfile -t -O ${#_args[@]} _args < policy/backup_args
	fi
fi

if [ -f backup_args ]; then
	mapfile -t -O ${#_args[@]} _args < backup_args
fi

set -x
restic backup --exclude-if-present=.nobackup \
	${_args+${_args[*]}} \
	$BACKUP_SOURCE_DIR \
	"$@"
