#!/bin/bash

set -eu

: ${RESTIC_GLOBAL_CONFIG:=$HOME/config}

set -o allexport; . "$RESTIC_GLOBAL_CONFIG"; set +o allexport

if [ -f config ]; then
	set -o allexport; . config; set +o allexport
fi

_args=()

if [ -f exclude ]; then
	_args+=(--exclude-file exclude)
fi

if [ -d policy ]; then
	policy_name=$(basename $(readlink policy))
	_args+=(--tag $policy_name)

	if [ -f "policy/backup_args" ]; then
		mapfile -t -O ${#_args[@]} _args < policy/backup_args
	fi
fi

if [ -f backup_args ]; then
	mapfile -t -O ${#_args[@]} _args < backup_args
fi

set -x
exec restic backup --exclude-if-present=.nobackup \
	${_args[*]} \
	$BACKUP_SOURCE_DIR \
	"$@"
