#!/bin/bash

set -eu

: ${RESTIC_GLOBAL_CONFIG:=$HOME/config}

set -o allexport; . "$RESTIC_GLOBAL_CONFIG"; set +o allexport

if [ -f config ]; then
	set -o allexport; . config; set +o allexport
fi

_args=()

if [ -d policy ]; then
	policy_name=$(basename $(readlink policy))
	_args+=(--tag $policy_name)

	if [ -f "policy/clean_args" ]; then
		mapfile -t -O ${#_args[@]} _args < policy/clean_args
	fi
fi

if [ -f clean_args ]; then
	mapfile -t -O ${#_args[@]} _args < clean_args
fi

set -x
exec restic forget \
	${_args[*]} \
	"$@"
