#!/bin/bash

_args=()

if [ -f exclude ]; then
	_args+=(--exclude-file exclude)
fi

if [ "$RESTIC_POLICY" ]; then
	_args+=(--tag $RESTIC_POLICY)

	if [ -f "$RESTIC_POLICY_DIR/$RESTIC_POLICY/backup_args" ]; then
		mapfile -t -O ${#_args[@]} _args \
			< "$RESTIC_POLICY_DIR/$RESTIC_POLICY/backup_args"
	fi
fi

if [ -f backup_args ]; then
	mapfile -t -O ${#_args[@]} _args < backup_args
fi

set -x
exec restic backup --exclude-if-present=.nobackup \
	${_args[*]} \
	$BACKUP_SOURCE_DIR \
	"$@"
